name: Test 3
on:
  push:
    branches: [ prod ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Merge prod->master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/luvk1412/demo.git
        git config user.name "test"
        git config user.email "test@test.com"
        git fetch origin master
        git fetch origin prod
        git checkout -b master origin/master
        git merge origin/prod --ff-only
        git push origin master
