name: Merge Prod -> master

on:
  push:
    branches: [ prod ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Merge prod->master ff_only
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "luvk1412"
          git config user.email "medusaalerts@flockgroups.com"
          git checkout -b master origin/master
          git pull --rebase
          git merge origin/prod
          git push origin master
