name: Auto Merge prod->master
on:
  push:
    branches: [ prod1 ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Merge prod->master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/luvk1412/demo
        git config user.name "talk-to"
        git config user.email "medusaalerts@flockgroups.com"
        git fetch origin master
        git checkout -b master origin/master
        git merge origin/prod --ff-only
        git push origin master
