name: Merge Prod -> master

on:
  push:
    branches: [ prod ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Merge prod->master ff_only
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "medusa-prod-auto-commit"
          git config user.email "medusaalerts@flockgroups.com"
          git fetch origin master
          git fetch origin prod
          git checkout master
          git pull --rebase
          git merge prod --ff --allow-unrelated-histories
          git push origin master
